{{- if .Values.blue.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ui-webapp.fullname" . }}-blue
  labels:
    app.kubernetes.io/name: {{ include "ui-webapp.name" . }}
    app.kubernetes.io/instance: {{ include "ui-webapp.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    slot: blue
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ui-webapp.name" . }}
      app.kubernetes.io/instance: {{ include "ui-webapp.name" . }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
      slot: blue
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "ui-webapp.name" . }}
        app.kubernetes.io/instance: {{ include "ui-webapp.name" . }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        slot: blue
    spec:   
      containers:
        - name: {{ .Values.container.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ .Values.service.name }}
              containerPort: {{ .Values.service.targetPort }}
              protocol: {{ .Values.service.protocol }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
{{- end }}
