apiVersion: v1
kind: Service
metadata:
  name: {{  .Values.label.name  }}
  labels:
    service: {{  .Values.label.name  }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }}
    targetPort: {{  .Values.service.targetPort }}
    name: {{ .Values.service.name }}
  selector:
    app: {{  .Values.label.name  }}
    # This determines which deployment the service is currently pointing to
    slot: {{ .Values.productionSlot }}
    