apiVersion: v1
kind: Service
metadata:
  name: {{  .Values.label.name  }}
  labels:
    service: {{  .Values.label.name  }}
    app.kubernetes.io/name: {{ include "ui-webapp.name" . }}
    app.kubernetes.io/instance: {{ include "ui-webapp.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    slot: {{ .Values.productionSlot }}
    app: {{  .Values.label.name  }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.targetPort }}
    nodePort: {{ .Values.service.nodePort }}
    name: http
  selector:
    app: {{  .Values.label.name  }}
    app.kubernetes.io/name: {{ include "ui-webapp.name" . }}
    app.kubernetes.io/instance: {{ include "ui-webapp.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    # This determines which deployment the service is currently pointing to
    slot: {{ .Values.productionSlot }}
    
