replicaCount: 1
container:
  name: ui
image:
  repository: rajputmarch2020/ui-webapp
  pullPolicy: IfNotPresent
  tag: ""

service:
  type: NodePort
  port: 8080
  targetPort: 8080
  nodePort: 30863
  nodeport: 31863
  name: ui

resources:
  limits:
    cpu: 150m
    memory: 512M
  requests:
    cpu: 150m
    memory: 512M

productionSlot: blue
stagingSlot: green

green:
  appVersion:
  tag: 
  #enabled: true

blue:
  appVersion:
  tag: 
  #enabled: true

label:
  name: ui-webapp
  service: ui
